### ISSUE TITLE
[$4,000] Substrate Wasm Contract Support

### ISSUE THREAD

**Issue by jiqiang90** [subquery/grants#25]
## Background

WebAssembly (Wasm) is used in Polkadot and Substrate as the compilation target for the runtime, but it's also a new smart contract platform built as an alternative to the Ethereum Virtual Machine (EVM). It's written in C, C++, or Rust and provides substantial improvements in execution speed, and the ability to use other languages than Solidity.

## Challenge

SubQuery has a goal of providing support for all execution environments in Substrate/Polkadot, including on chain data, smart contracts in EVM, and smart contracts in WebAssembly (Wasm). This will allow all application developers to leverage the same excellent infrastructure tools across the ecosystem to build the next generation of applications.

## Submission Requirements

You will create a new instance of a data processor similar to the existing [Substrate Frontier EVM processor](https://github.com/subquery/subql/blob/main/packages/contract-processors/src/frontierEvm.ts). It must connect to a Wasm compatible chain and process the messages from the Wasm execution in a [similar way](https://university.subquery.network/build/substrate-evm.html) to how messages from the [Substrate Frontier EVM processor are processed](https://github.com/subquery/subql/blob/main/packages/contract-processors/src/frontierEvm.ts). You should then be able to use these in a handlers just like how a traditional SubQuery project works

A working project manifest might look like the following:

```yml
dataSources:
  - kind: substrate/Wasm
    startBlock: 1
    processor:
      file: "./node_modules/@subql/contract-processors/dist/substrateWasm.js"
      options:
        # Any options relating to the smart contract we are executing      
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleWasmEvent
          kind: substrate/SubstrateWasmEvent
          filter:
            # Any filters that make sense
        - handler: handleWasmMessage
          kind: substrate/SubstrateWasmMessage
          filter:
            # Any filters that make sense
```

## Judging Criteria

- How similar your implementation is to the existing Substrate EVM data processor implementation for consistency
- How well you implement different handlers that make sense for wasm
- Bonus points if your solution works with minimal configuration for other wasm implementations (like Astar)
- How much documentation you provide
- The test cases quality and coverage

## Resources

- [Gear Network Wasm Documentation](https://wiki.gear-tech.io/developing-contracts/messaging)
- [Example Frontier EVM Processor Codebase](https://github.com/subquery/subql/blob/main/packages/contract-processors/src/frontierEvm.ts)
- [Example Frontier EVM Documentation](https://university.subquery.network/build/substrate-evm.html)
- [Example Frontier EVM SubQuery Project](https://github.com/subquery/tutorials-frontier-evm-starter)
